from flask import Flask, render_template, jsonify, request, send_from_directory
import subprocess
import json
import os
import csv
import io

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import pagesizes
from reportlab.lib.units import inch

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
BINARY_PATH = os.path.join(BASE_DIR, "puster")
DATA_PATH = os.path.join(BASE_DIR, "monitor_data.json")

app = Flask(__name__)


def load_data():
    """Load scan results from the JSON file generated by the C binary."""
    if not os.path.exists(DATA_PATH):
        return None
    with open(DATA_PATH, "r") as f:
        return json.load(f)


@app.route("/")
def home():
    """Render the main dashboard page."""
    return render_template("index.html")


@app.route("/scan")
def scan():
    """Execute the puster binary to scan active network connections."""
    try:
        result = subprocess.run(
            [BINARY_PATH],
            capture_output=True,
            text=True,
            timeout=30
        )
        if result.returncode != 0:
            return jsonify({
                "status": "error",
                "message": result.stderr.strip()
            }), 500
        return jsonify({
            "status": "completed",
            "message": result.stdout.strip()
        })
    except subprocess.TimeoutExpired:
        return jsonify({
            "status": "error",
            "message": "Scan timed out"
        }), 500
    except FileNotFoundError:
        return jsonify({
            "status": "error",
            "message": "Binary not found. Compile with: gcc -o puster puster.c"
        }), 500


@app.route("/data")
def data():
    """Return the full JSON dataset from the last scan."""
    datos = load_data()
    if datos is None:
        return jsonify({"error": "No data found. Run a scan first."}), 404
    return jsonify(datos)


@app.route("/api/alerts")
def api_alerts():
    """Return alerts with optional filtering by risk level, process, or port."""
    datos = load_data()
    if datos is None:
        return jsonify({"error": "No data found"}), 404

    alerts = datos.get("alerts", [])
    risk_filter = request.args.get("risk", "").upper()
    process_filter = request.args.get("process", "").lower()
    port_filter = request.args.get("port", "")

    if risk_filter:
        alerts = [a for a in alerts if a.get("risk", "").upper() == risk_filter]
    if process_filter:
        alerts = [a for a in alerts if process_filter in a.get("process", "").lower()]
    if port_filter:
        alerts = [a for a in alerts if a.get("remote_port", "") == port_filter]

    return jsonify({
        "metadata": datos.get("metadata", {}),
        "summary": {
            "total_connections": len(alerts),
            "low": sum(1 for a in alerts if a.get("risk") == "LOW"),
            "medium": sum(1 for a in alerts if a.get("risk") == "MEDIUM"),
            "high": sum(1 for a in alerts if a.get("risk") == "HIGH"),
        },
        "alerts": alerts
    })


@app.route("/export/csv")
def export_csv():
    """Export alerts data as a downloadable CSV file."""
    datos = load_data()
    if datos is None:
        return jsonify({"error": "No data found"}), 404

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Process", "PID", "Protocol", "Remote IP", "Remote Port",
        "Local IP", "Local Port", "Risk"
    ])

    for alert in datos.get("alerts", []):
        writer.writerow([
            alert.get("process", ""),
            alert.get("pid", ""),
            alert.get("protocol", ""),
            alert.get("remote_ip", ""),
            alert.get("remote_port", ""),
            alert.get("local_ip", ""),
            alert.get("local_port", ""),
            alert.get("risk", ""),
        ])

    csv_content = output.getvalue()
    output.close()

    response = app.make_response(csv_content)
    response.headers["Content-Type"] = "text/csv"
    response.headers["Content-Disposition"] = \
        "attachment; filename=puster_report.csv"
    return response


@app.route("/export/pdf")
def export_pdf():
    """Export alerts data as a downloadable PDF report (in-memory, no temp files)."""
    datos = load_data()
    if datos is None:
        return jsonify({"error": "No data available"}), 400

    # Build PDF in memory to avoid file race conditions
    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=pagesizes.letter)
    elements = []
    styles = getSampleStyleSheet()

    meta = datos.get("metadata", {})
    summary = datos.get("summary", {})

    elements.append(Paragraph(
        "Puster 3.5 - Security Report", styles["Title"]))
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        f"Host: {meta.get('hostname', 'unknown')}", styles["Normal"]))
    elements.append(Paragraph(
        f"Timestamp: {meta.get('timestamp', 'N/A')}", styles["Normal"]))
    elements.append(Paragraph(
        f"Total Connections: {summary.get('total_connections', 0)}",
        styles["Normal"]))
    elements.append(Paragraph(
        f"LOW: {summary.get('low', 0)} | "
        f"MEDIUM: {summary.get('medium', 0)} | "
        f"HIGH: {summary.get('high', 0)}",
        styles["Normal"]))
    elements.append(Spacer(1, 0.5 * inch))

    table_data = [["Process", "PID", "Remote IP", "Port",
                    "Protocol", "Risk"]]
    for alert in datos.get("alerts", []):
        table_data.append([
            alert.get("process", ""),
            alert.get("pid", ""),
            alert.get("remote_ip", ""),
            alert.get("remote_port", ""),
            alert.get("protocol", ""),
            alert.get("risk", ""),
        ])

    table = Table(table_data)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
    ]))

    elements.append(table)
    doc.build(elements)

    # Send PDF directly from memory
    pdf_buffer.seek(0)
    return app.make_response(pdf_buffer.getvalue()), 200, {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=puster_report.pdf"
    }


if __name__ == "__main__":
    port = int(os.environ.get("PUSTER_PORT", 5000))
    host = os.environ.get("PUSTER_HOST", "127.0.0.1")
    debug = os.environ.get("PUSTER_DEBUG", "false").lower() == "true"
    app.run(host=host, port=port, debug=debug)
